name: Automacao Sorte Facil
on:
  workflow_dispatch: # Isso faz o botão aparecer para teste manual
  schedule:
    - cron: '1 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Pillow
        run: pip install pillow

      - name: Gerar Imagem
        run: python main.py

      - name: Salvar no Git
        run: |
          git config --global user.name "Sorte Facil Bot"
          git config --global user.email "bot@sortefacil.com"
          git add lotofacil.jpg
          git commit -m "Update imagem" || echo "Sem mudanças"
          git push
          
